### ISSUE TITLE
Veams.EVENTS.resize should not be "resize"

### ISSUE THREAD

**Issue by andy-gutsche** [Veams/veams-js#3]
Because of the fact that `Veams.Vent` points to the document, `Veams.EVENTS.resize` should be something else than 'resize'. Otherwise there would be no difference between the native browser `resize` reaching the `document`-element and our throttled width-based resize-event triggered by the media-query-handler plugin.

**Comment by Sebastian-Fitzner** [comment]
not anymore, it is already fixed!

**Comment by Sebastian-Fitzner** [comment]
Please make sure, that you test the last version before opening a ticket :P
